### ISSUE TITLE
/wrote command not working with project shortname

### ISSUE THREAD

**Issue by KmacKatie** [cwarwicker/discord-Writer-Bot#131]
Multiple instances of the /wrote command not recognising the project shortname. Counts words written to total, but does not add to the project shortname.

**Comment by Starlight220** [comment]
With optional parameters you really have to make sure that Discord actually understands that you're supplying the parameter; sometimes you can write the command and everything and Discord just sees it as extra trailing text and ignores it. The UI on desktop/web is annoying in this regard, I hope that Discord improves it soon.

We're aware of this issue, and there isn't much we can do:
We can make that parameter required, but that will be an inconvenience when using the command without the optional parameter.
Autocomplete could help, but we can't implement that yet. We will when we can though, so that will probably be the solution.
